/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.79
 * Generated at: 2022-07-01 00:36:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.payment;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.gushipsam.payment.dao.MemberDTO;
import com.gushipsam.payment.dao.CartDTO;
import java.text.DecimalFormat;

public final class checkout06_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/0900_GB_KSH/jsp/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp22/wtpwebapps/93test/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/payment/../header/header.jsp", Long.valueOf(1656635277000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1656635277000L));
    _jspx_dependants.put("/payment/../footer/footer.jsp", Long.valueOf(1656635277000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.gushipsam.payment.dao.MemberDTO");
    _jspx_imports_classes.add("com.gushipsam.payment.dao.CartDTO");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.text.DecimalFormat");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write(" 	<!--  숫자에 콤마 붙이기 위한 숫자포맷 라이브러리 -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write('\n');

	List<CartDTO> checkoutList = (List) request.getAttribute("checkoutList");
	MemberDTO memberInfo = (MemberDTO) request.getAttribute("memberInfo");
	
	int shippingCost = 2500;
	
	DecimalFormat df = new DecimalFormat("###,###"); // df.format(숫자)로 콤마 보이게 가능
	
	if(checkoutList.size() == 0) response.sendRedirect(request.getContextPath() + "/main/main.jsp");


      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>구심삽 주문결제</title>\n");
      out.write("<script src=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>구십삼</title>\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/main_css.css\">\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/slick.css\">\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/header.css\">\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/footer.css\">\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/minsu.css\">\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/common06.css\">\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/cart06.css\">\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/checkout06.css\">\n");
      out.write("	<link rel=\"shortcut icon\" href=\"../img/gushipsam_icon.ico\">	\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/Mypage.css\">\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/User-Info.css\">\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/User-InfoUp.css\">\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/OrderList-Page.css\">\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/secession.css\">\n");
      out.write("	<script type=\"text/javascript\" src=\"../js/slick.min.js\"></script> \n");
      out.write("	<script type=\"text/javascript\" src=\"../js/slide.js\"></script> \n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	");
      if (_jspx_meth_c_005fset_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("	<div>\n");
      out.write("		<!-- 로고 -->\n");
      out.write("		<div class=\"login_search\">\n");
      out.write("			<a href=\"#\"onclick=\"location.href='../main/main.jsp'\" class= logo><img src= ../img/logo.png></a>\n");
      out.write(" 			<!-- 로그인, 로그아웃, 장바구니, 고객센터 -->\n");
      out.write(" 			<ul class = nav1>\n");
      out.write("						<li class= service><a href= \"../service/minsu1.sv\">고객센터 </a></li>\n");
      out.write("						<li class= basket><a href= \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/payment/cart.pay\">장바구니 </a></li>\n");
      out.write("				");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("			</ul>\n");
      out.write("			<!-- 검색창 -->\n");
      out.write("		<div class=\"search1\">\n");
      out.write("			<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/goods/SearchGoods.spm\" method=\"post\" name=\"searchForm\">\n");
      out.write("				<input placeholder=\"Search\" class= 'search_main' name=\"searchtext\">\n");
      out.write("				<a class=\"btn\" href=\"javascript:document.searchForm.submit()\" role=\"button\">\n");
      out.write("					<img src=\"https://s3.ap-northeast-2.amazonaws.com/cdn.wecode.co.kr/icon/search.png\">\n");
      out.write("				</a>\n");
      out.write("			</form>\n");
      out.write("		</div>\n");
      out.write("			<!-- 카테고리 -->\n");
      out.write("			<div class=\"category\">\n");
      out.write("				<div class= nav2> \n");
      out.write("					<ul>\n");
      out.write("						<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/goods/goodsList.goods?gCatg=냉장고\" class=\"a\">냉장고</a>\n");
      out.write("							<ul>\n");
      out.write("								<li><a href=\"상품페이지 경로\" style=\"color:blue;\">SAMSUNG</a></li>\n");
      out.write("								<li><a href=\"상품페이지 경로\" style=\"color:red;\">LG</a></li>\n");
      out.write("							</ul>\n");
      out.write("						</li>\n");
      out.write("						<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/goods/goodsList.goods?gCatg=세탁기\" class=\"a\">세탁기</a>\n");
      out.write("							<ul>\n");
      out.write("								<li><a href=\"상품페이지 경로\" style=\"color:blue;\">SAMSUNG</a></li>\n");
      out.write("								<li><a href=\"상품페이지 경로\" style=\"color:red;\">LG</a></li>\n");
      out.write("							</ul></li>\n");
      out.write("						<li><a  href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/goods/goodsList.goods?gCatg=TV\" class=\"a\">TV</a>\n");
      out.write("							<ul>\n");
      out.write("								<li><a href=\"상품페이지 경로\" style=\"color:blue;\">SAMSUNG</a></li>\n");
      out.write("								<li><a href=\"상품페이지 경로\" style=\"color:red;\">LG</a></li>\n");
      out.write("							</ul></li>\n");
      out.write("						<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/goods/goodsList.goods?gCatg=에어컨\" class=\"a\">에어컨</a>\n");
      out.write("							<ul>\n");
      out.write("								<li><a href=\"상품페이지 경로\" style=\"color:blue;\">SAMSUNG</a></li>\n");
      out.write("								<li><a href=\"상품페이지 경로\" style=\"color:red;\">LG</a></li>\n");
      out.write("								<li><a href=\"상품페이지 경로\" style=\"color:black;\">WINIA</a></li>\n");
      out.write("							</ul></li>\n");
      out.write("		\n");
      out.write("						<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/goods/goodsList.goods?gCatg=컴퓨터\" class=\"a\">컴퓨터</a>\n");
      out.write("							<ul>\n");
      out.write("								<li><a href=\"상품페이지 경로\" style=\"color:blue;\">SAMSUNG</a></li>\n");
      out.write("								<li><a href=\"상품페이지 경로\" style=\"color:red;\">LG</a></li>\n");
      out.write("								<li><a href=\"상품페이지 경로\" style=\"color:black;\">APPLE</a></li>\n");
      out.write("							</ul>\n");
      out.write("						</li>\n");
      out.write("					</ul>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div> \n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("<body id=\"payment\">\n");
      out.write("	<section id='checkout'>\n");
      out.write("		<br>\n");
      out.write("		<div id=\"title_big\">주문/결제</div>\n");
      out.write("		<table id=\"order_tb\">\n");
      out.write("			<colgroup>\n");
      out.write("				<col width=\"62.5%\">\n");
      out.write("				<col width=\"15%\">\n");
      out.write("				<col width=\"7.5%\">\n");
      out.write("				<col width=\"15%\">\n");
      out.write("			</colgroup>\n");
      out.write("			<thead>\n");
      out.write("				<tr>\n");
      out.write("					<td colspan=\"4\">\n");
      out.write("						<h3 id=\"title\">구십삼 배송상품</h3>\n");
      out.write("					</td>\n");
      out.write("				</tr>\n");
      out.write("				<tr class=\"table_top\">\n");
      out.write("					<td>\n");
      out.write("						<div class=\"align_center\">상품정보</div>\n");
      out.write("					</td>\n");
      out.write("					<td>\n");
      out.write("						<div class=\"align_center\">판매가</div>\n");
      out.write("					</td>\n");
      out.write("					<td>\n");
      out.write("						<div class=\"align_center\">수량</div>\n");
      out.write("					</td>\n");
      out.write("					<td>\n");
      out.write("						<div class=\"align_center\">구매가</div>\n");
      out.write("					</td>\n");
      out.write("				</tr>\n");
      out.write("			</thead>\n");
      out.write("			<tbody>\n");
      out.write("				");
 for (CartDTO item : checkoutList ) { 
      out.write("\n");
      out.write("				<tr>\n");
      out.write("					<td>\n");
      out.write("						<table class=\"goods_tb\">\n");
      out.write("							<colgroup>\n");
      out.write("								<col width=\"20%\">\n");
      out.write("								<col width=\"80%\">\n");
      out.write("							</colgroup>\n");
      out.write("							<tr>\n");
      out.write("								<td rowspan=\"2\">\n");
      out.write("									");

										String foldername = null;
										String catg = item.getgCATG();
										String img = item.getgIMGS();
										
										switch (catg) {
										case "냉장고" : foldername= "fridge"; break;
										case "세탁기" : foldername= "washer"; break;
										case "TV" : foldername= "tv"; break;
										case "에어컨" : foldername= "ac"; break;
										case "컴퓨터" : foldername= "pc"; break;
										}
									
      out.write("\n");
      out.write("									<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/goods/goodsDetail.goods?gID=");
      out.print(item.getgID() );
      out.write("\">\n");
      out.write("										<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/");
      out.print(foldername );
      out.write('/');
      out.print(img );
      out.write("\" style=\"width:100%\">\n");
      out.write("									</a>\n");
      out.write("								</td>\n");
      out.write("								<td>");
      out.print(item.getgBRAND());
      out.write("</td>\n");
      out.write("							</tr>\n");
      out.write("							<tr>\n");
      out.write("								<td>");
      out.print(item.getgNAME());
      out.write("</td>\n");
      out.write("							</tr>\n");
      out.write("						</table>\n");
      out.write("					</td>\n");
      out.write("					");
 int price = item.getgPRICE(); int qty = item.getcQTY(); 
      out.write("\n");
      out.write("					<td>\n");
      out.write("						<div class=\"align_center\">");
      out.print( df.format(price) );
      out.write("</div>\n");
      out.write("					</td>\n");
      out.write("					<td>\n");
      out.write("						<div class=\"align_center\">");
      out.print( qty );
      out.write("</div>\n");
      out.write("					</td>\n");
      out.write("					<td>\n");
      out.write("						<div class=\"align_center\">");
      out.print( df.format(price*qty) );
      out.write("</div>\n");
      out.write("					</td>\n");
      out.write("				</tr>\n");
      out.write("				");
 } 
      out.write("\n");
      out.write("			</tbody>\n");
      out.write("		</table>		\n");
      out.write("		<br>\n");
      out.write("	\n");
      out.write("		<table id=\"pay_tb\">\n");
      out.write("			<colgroup>\n");
      out.write("				<col width=\"600\">\n");
      out.write("				<col width=\"*\">\n");
      out.write("			</colgroup>\n");
      out.write("			<thead>\n");
      out.write("				<tr>\n");
      out.write("					<td class=\"real_top\" style=\"border-right: 20px solid transparent;\"><h3 id=\"title1\">배송지정보</h3></td>\n");
      out.write("					<td class=\"real_top\"><h3 id=\"title2\">최종 결제정보</h3></td>\n");
      out.write("				</tr>\n");
      out.write("			</thead>\n");
      out.write("			<tr>\n");
      out.write("				<td style=\"border-right: 20px solid transparent\">\n");
      out.write("					<table id=\"delivery_tb\" class=\"sub_tb\">\n");
      out.write("						<colgroup>\n");
      out.write("							<col width=\"82\">\n");
      out.write("							<col width=\"*\">\n");
      out.write("						</colgroup>\n");
      out.write("						<tr>\n");
      out.write("						");

							String name = memberInfo.getUsername(), phone = memberInfo.getUserphone();
						
      out.write("\n");
      out.write("							<td>	받는분	</td>\n");
      out.write("							<td>\n");
      out.write("								<span style=\"color:red; font-weight:bold\">*</span>\n");
      out.write("								<input type=\"text\" id=\"receiver\" value=\"");
      out.print( name );
      out.write("\" style=\"width:300px\">\n");
      out.write("							</td>\n");
      out.write("						</tr>\n");
      out.write("						<tr>\n");
      out.write("							<td>	연락처1	</td>\n");
      out.write("							<td>	\n");
      out.write("								<span style=\"color:red; font-weight:bold\">*</span>\n");
      out.write("								<input type=\"number\" id=\"phone1\" value=\"");
      out.print( phone.substring(0,3) );
      out.write("\" style=\"width:80px\"> - <input type=\"number\" id=\"phone2\" value=\"");
      out.print( phone.substring(3,7)  );
      out.write("\" style=\"width:80px\"> - <input type=\"number\" id=\"phone3\" value=\"");
      out.print( phone.substring(7,11)  );
      out.write("\" style=\"width:80px\">	\n");
      out.write("							</td>\n");
      out.write("						</tr>	\n");
      out.write("						<tr>\n");
      out.write("							<td>	연락처2	</td>\n");
      out.write("							<td>										<span style=\"color:transparent; font-weight:bold\">*</span>\n");
      out.write("								<input type=\"number\" style=\"width:80px\"> - <input type=\"number\" style=\"width:80px\"> - <input type=\"number\" style=\"width:80px\">	\n");
      out.write("							</td>\n");
      out.write("						</tr>\n");
      out.write("						<tr>\n");
      out.write("							<td rowspan=\"3\">	주소	</td>\n");
      out.write("							<td>	\n");
      out.write("								<span style=\"color:red; font-weight:bold\">*</span> \n");
      out.write("								<input type=\"text\" id=\"sample6_postcode\" placeholder=\"우편번호\" style=\"width:80px\">\n");
      out.write("								<input type=\"button\" id=\"address_button\" onclick=\"sample6_execDaumPostcode()\" value=\"우편번호 찾기\" style=\"width:100px\">\n");
      out.write("							</td>\n");
      out.write("						</tr>\n");
      out.write("						<tr>\n");
      out.write("							<td>\n");
      out.write("								<span style=\"color:red;; font-weight:bold\">*</span>\n");
      out.write("								<input type=\"text\" id=\"sample6_address\" placeholder=\"주소\" style=\"width:400px\">\n");
      out.write("							</td>\n");
      out.write("						</tr>\n");
      out.write("						<tr>\n");
      out.write("							<td>\n");
      out.write("								<span style=\"color:red; font-weight:bold\">*</span>\n");
      out.write("								<input type=\"text\" id=\"sample6_detailAddress\" placeholder=\"상세주소\" style=\"width:250px\">\n");
      out.write("								<input type=\"text\" id=\"sample6_extraAddress\" placeholder=\"참고항목\" style=\"width:150px\">\n");
      out.write("							</td>\n");
      out.write("						</tr>\n");
      out.write("						<tr>\n");
      out.write("							<td>\n");
      out.write("							</td>\n");
      out.write("							<td>	\n");
      out.write("								<span style=\"color:red; font-weight:bold\">* 필수작성란</span>\n");
      out.write("							\n");
      out.write("<!-- 								<span style=\"color:transparent; font-weight:bold\">*</span> -->\n");
      out.write("<!-- 								<input type=\"text\" placeholder=\"배송메세지를 입력해주세요\" style=\"width:450px\">	 -->\n");
      out.write("							</td>\n");
      out.write("						</tr>\n");
      out.write("					</table>	\n");
      out.write("				</td>\n");
      out.write("				<td rowspan=\"3\" style=\"text-align:right\">\n");
      out.write("					");
 int checkoutSum = 0;	
					for (CartDTO item : checkoutList ) { 
						checkoutSum += item.getgPRICE() * item.getcQTY();
					} 
      out.write("\n");
      out.write("					<h2 id=\"margin_fix1\">최종 결제금액 : ");
      out.print( df.format(checkoutSum+shippingCost));
      out.write(" 원</h2>\n");
      out.write("					<h3 id=\"margin_fix2\">상품금액 : ");
      out.print( df.format(checkoutSum) );
      out.write(" 원 </h3>\n");
      out.write("					<h3 id=\"margin_fix3\">배송비 : ");
      out.print( df.format(shippingCost) );
      out.write(" 원</h3>\n");
      out.write("					<br>\n");
      out.write("					<input type=\"button\" id=\"pay_button\" value=\"결제하기\" onclick=\"checkoutnpay();\">\n");
      out.write("				</td>\n");
      out.write("			</tr>\n");
      out.write("			<tr>\n");
      out.write("				<td class=\"real_top\"><h3 id=\"title3\">결제수단 선택</h3></td>\n");
      out.write("			</tr>\n");
      out.write("			<tr>\n");
      out.write("				<td style=\"border-right: 20px solid transparent; height:150px\">\n");
      out.write("					<p id=\"margin_fix4\">\n");
      out.write("						<input type=\"radio\" name=\"paymethod\" value=\"신용카드\" checked>신용카드 &nbsp;\n");
      out.write("						<input type=\"radio\" name=\"paymethod\" value=\"무통장입금\">무통장입금 &nbsp;\n");
      out.write("						<input type=\"radio\" name=\"paymethod\" value=\"계좌이체\">계좌이체 &nbsp;\n");
      out.write("						<input type=\"radio\" name=\"paymethod\" value=\"네이버페이\">네이버페이 &nbsp;\n");
      out.write("						<input type=\"radio\" name=\"paymethod\" value=\"휴대폰결제\">휴대폰결제\n");
      out.write("					</p>	\n");
      out.write("					<table id=\"creditcard_tb\"  class=\"sub_tb\">\n");
      out.write("						<colgroup>\n");
      out.write("							<col width=\"82\">\n");
      out.write("							<col width=\"*\">\n");
      out.write("						</colgroup>\n");
      out.write("						<tr>\n");
      out.write("							<td>	카드종류	</td>\n");
      out.write("							<td>\n");
      out.write("								<select name=\"card\" style=\"width:110px\">\n");
      out.write("								    <option value=\"BC카드\">BC카드</option>\n");
      out.write("								    <option value=\"외환카드\">외환카드</option>\n");
      out.write("								    <option value=\"하나비자\">하나비자</option>\n");
      out.write("								    <option value=\"우리카드\">우리카드</option>\n");
      out.write("								    <option value=\"신협카드\">신협카드</option>\n");
      out.write("								    <option value=\"수협카드\">수협카드</option>\n");
      out.write("								    <option value=\"전북카드\">전북카드</option>\n");
      out.write("								    <option value=\"씨티카드\">씨티카드</option>\n");
      out.write("								    <option value=\"삼성카드\">삼성카드</option>\n");
      out.write("								    <option value=\"신한카드\">신한카드</option>\n");
      out.write("								    <option value=\"현대카드\">현대카드</option>\n");
      out.write("								    <option value=\"롯데카드\">롯데카드</option>\n");
      out.write("								    <option value=\"KB카드\">KB카드</option>\n");
      out.write("								    <option value=\"NH카드\">NH카드</option>\n");
      out.write("								    <option value=\"카카오뱅크\">카카오뱅크</option>\n");
      out.write("								</select>\n");
      out.write("							</td>\n");
      out.write("						</tr>\n");
      out.write("						<tr>\n");
      out.write("							<td>	할부종류	</td>\n");
      out.write("							<td>	\n");
      out.write("								<select name=\"installment\" style=\"width:110px\">\n");
      out.write("								    <option value=\"일시불\">일시불</option>\n");
      out.write("								    <option value=\"2개월 [무이자]\">2개월 [무이자]</option>\n");
      out.write("								    <option value=\"3개월 [무이자]\">3개월 [무이자]</option>\n");
      out.write("								    <option value=\"4개월 [무이자]\">4개월 [무이자]</option>\n");
      out.write("								    <option value=\"5개월 [무이자]\">5개월 [무이자]</option>\n");
      out.write("								    <option value=\"6개월 [무이자]\">6개월 [무이자]</option>\n");
      out.write("								    <option value=\"7개월 [무이자]\">7개월 [무이자]</option>\n");
      out.write("								    <option value=\"8개월\">8개월</option>\n");
      out.write("								    <option value=\"9개월\">9개월</option>\n");
      out.write("								    <option value=\"10개월\">10개월</option>\n");
      out.write("								    <option value=\"11개월\">11개월</option>\n");
      out.write("								    <option value=\"12개월\">12개월</option>\n");
      out.write("\n");
      out.write("								</select>	\n");
      out.write("							</td>\n");
      out.write("						</tr>\n");
      out.write("						<tr>\n");
      out.write("							<td colspan=\"2\">\n");
      out.write("								<ul id=\"explain1\">\n");
      out.write("									<li>&lt;카카오뱅크 체크카드 혜택&gt;</li>\n");
      out.write("									<li>3만원 이상 결제 시 <span style=\"color:#F27370\">2천원 캐시백</span></li>\n");
      out.write("									<li>온/오프라인에서 <span style=\"color:#F27370\">월 1회 사용 가능</span></li>\n");
      out.write("									<li>신용/체크카드 결제금액이 30만원 이상인 경우 공인인증서가 필요합니다.</li>\n");
      out.write("								</ul>\n");
      out.write("							</td>\n");
      out.write("						</tr>					\n");
      out.write("					</table>\n");
      out.write("					<table id=\"nobank_tb\"  class=\"sub_tb\">\n");
      out.write("						<colgroup>\n");
      out.write("							<col width=\"82\">\n");
      out.write("							<col width=\"*\">\n");
      out.write("						</colgroup>\n");
      out.write("						<tr>\n");
      out.write("							<td>	은행명	</td>\n");
      out.write("							<td>\n");
      out.write("								<select name=\"bank\" style=\"width:100px\">\n");
      out.write("								    <option value=\"외환카드\">기업</option>\n");
      out.write("								    <option value=\"하나비자\">국민</option>\n");
      out.write("								    <option value=\"우리카드\">수협</option>\n");
      out.write("								    <option value=\"신협카드\">농협</option>\n");
      out.write("								    <option value=\"수협카드\">우리</option>\n");
      out.write("								    <option value=\"전북카드\">대구</option>\n");
      out.write("								    <option value=\"씨티카드\">부산</option>\n");
      out.write("								    <option value=\"삼성카드\">경남</option>\n");
      out.write("								    <option value=\"신한카드\">우체국</option>\n");
      out.write("								    <option value=\"현대카드\">하나</option>\n");
      out.write("								    <option value=\"롯데카드\">신한</option>\n");
      out.write("								</select>\n");
      out.write("							</td>\n");
      out.write("						</tr>\n");
      out.write("						<tr>\n");
      out.write("							<td>	입금기한	</td>\n");
      out.write("							<td>	<div id=\"tomorrow_date\"></div></td>\n");
      out.write("						</tr>\n");
      out.write("						<tr>\n");
      out.write("							<td>	입금자명	</td>\n");
      out.write("							<td>	<input type=\"text\" value=\"");
      out.print( name );
      out.write("\" style=\"width:100px\"></td>\n");
      out.write("						</tr>					\n");
      out.write("					</table>\n");
      out.write("					<table id=\"account_tb\"  class=\"sub_tb\">\n");
      out.write("						<colgroup>\n");
      out.write("							<col width=\"82\">\n");
      out.write("							<col width=\"*\">\n");
      out.write("						</colgroup>\n");
      out.write("						<tr>\n");
      out.write("							<td style=\"vertical-align: middle;\"> 결제안내	</td>\n");
      out.write("							<td>\n");
      out.write("								<ul id=\"explain2\">\n");
      out.write("									<li>계좌이체로 결제 완료시 본인 계좌에서 즉시 이체 처리됩니다.</li>\n");
      out.write("									<li>실시간 계좌이체는 은행별 이용시간이 다를 수 있습니다.</li>\n");
      out.write("								</ul>\n");
      out.write("							</td>\n");
      out.write("						</tr>										\n");
      out.write("					</table>\n");
      out.write("					<table id=\"naverpay_tb\"  class=\"sub_tb\">\n");
      out.write("						<tr>\n");
      out.write("							<td>				\n");
      out.write("								<ul id=\"explain3\">\n");
      out.write("									<li style=\"font-weight:bold; list-style-type:none;\"> &lt;네이버페이 유의사항&gt;</li>\n");
      out.write("									<li>주문 변경 시 카드사 혜택 및 할부 적용 여부는 해당 카드사 정책에 따라 변경될 수 있습니다.</li>\n");
      out.write("									<li>네이버페이로 결제 시, 제휴카드 할인/적립(CJ카드, 임직원할인 포함)이 적용되지 않습니다.</li>\n");
      out.write("									<li>현금영수증 확인은 네이버페이 홈페이지에서 확인 가능합니다. (네이버페이 홈 > 결제내역)</li>\n");
      out.write("									<li>네이버페이 고객센터 : 1588-3819</li>\n");
      out.write("								</ul>\n");
      out.write("							</td>\n");
      out.write("						</tr>										\n");
      out.write("					</table>\n");
      out.write("					<table id=\"phonepay_tb\"  class=\"sub_tb\">\n");
      out.write("						<colgroup>\n");
      out.write("							<col width=\"82\">\n");
      out.write("							<col width=\"*\">\n");
      out.write("						</colgroup>\n");
      out.write("						<tr>\n");
      out.write("							<td style=\"vertical-align: middle;\"> 결제안내	</td>\n");
      out.write("							<td>\n");
      out.write("								<ul id=\"explain4\">\n");
      out.write("									<li>휴대폰 결제는 100만원까지 결제가 가능합니다.</li>\n");
      out.write("									<li>한도문의는 모빌리언스(1600-0523), 다날(1566-3355), 페이레터(1599-7591)로 문의주시기 바랍니다.</li>\n");
      out.write("								</ul>\n");
      out.write("							</td>\n");
      out.write("						</tr>										\n");
      out.write("					</table>\n");
      out.write("				</td>\n");
      out.write("			</tr>\n");
      out.write("		</table>\n");
      out.write("	</section>\n");
      out.write("	<div style=\"height:130px\"></div>\n");
      out.write("	");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<!--  	<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/footer.css\"> -->\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<!-- footer -->\n");
      out.write("	<footer>\n");
      out.write("		<p>\n");
      out.write("			<span>상호명 : 구십삼</span>\n");
      out.write("			<span>대표 : 김시우</span><br/>\n");
      out.write("			<span>이메일 : 93jow@gmail.com</span><br>\n");
      out.write("			<span>주소 : 서울 강남구 테헤란로 146</span><br/>\n");
      out.write("			<span>사업자등록번호 : 000-00-0000</span><br/>\n");
      out.write("			<span>Copyright 2022. cocoder. All Rights Reserved.</span>\n");
      out.write("		</p>\n");
      out.write("			<a  href=\"\"   target='blank'>사이트관리자</a>\n");
      out.write("			<a  href=\"\"   target='blank'>회사소개</a>\n");
      out.write("			<a  href=\"#\"  onclick=\"location.href='../main/map.jsp'\"> 찾아오시는 길</a>\n");
      out.write("			<a  href=\"#\"  onclick=\"location.href='../main/personalinfrom.jsp'\"> 개인정보처리방침</a>\n");
      out.write("	</footer>\n");
      out.write("	\n");
      out.write("	<script>\n");
      out.write("	\n");
      out.write("	</script>\n");
      out.write("</html>\n");
      out.write("</body>");
      out.write("\n");
      out.write("</body>\n");
      out.write("<script>\n");
      out.write("	function checkoutnpay(){\n");
      out.write("		\n");
      out.write("		//필수 입력란\n");
      out.write("		let checkout_inputs = [$('#phone1').val(), $('#phone2').val(), $('#phone3').val(),\n");
      out.write("									$('#sample6_address').val(), $('#sample6_detailAddress').val(), $('#receiver').val(), $('#sample6_postcode').val()];\n");
      out.write("		\n");
      out.write("		let ophone = checkout_inputs[0] + checkout_inputs[1] + checkout_inputs[2];\n");
      out.write("		let oaddress = checkout_inputs[3] +\" \"+ checkout_inputs[4] + $('#sample6_extraAddress').val();\n");
      out.write("		\n");
      out.write("		for(let i = 0 ; i< checkout_inputs.length;i++){\n");
      out.write("			input = checkout_inputs[i];\n");
      out.write("			if(input==null || input==\"\"){\n");
      out.write("				alert(\"배송정보를 정확히 입력해주세요.\");\n");
      out.write("				return false;\n");
      out.write("			}\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		let total_amount = \"");
      out.print( df.format(checkoutSum+shippingCost));
      out.write("\";\n");
      out.write("		let paymethod = $('input[name=\"paymethod\"]:checked').val();\n");
      out.write("		let postposition =\"를\";\n");
      out.write("		if(paymethod ==\"무통장입금\") postposition = \"을\";\n");
      out.write("		\n");
      out.write("		if(! confirm( paymethod + postposition + \" 사용하여 \" + total_amount + \" 원을 결제하시겠습니까?\") ) {\n");
      out.write("			return false;\n");
      out.write("		} else {\n");
      out.write("			alert('주문/결제가 완료되었습니다.');\n");
      out.write("		}\n");
      out.write("\n");
      out.write("		");
 for (CartDTO item : checkoutList ) {
			pageContext.setAttribute("cID",item.getcID());
			pageContext.setAttribute("directgID",item.getgID());
			pageContext.setAttribute("directoQTY",item.getcQTY());
 		
      out.write("  \n");
      out.write("			cid_arr.push(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\n");
      out.write("			let directgID = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${directgID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("			let directoQTY = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${directoQTY}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("		");
}
      out.write("\n");
      out.write("					\n");
      out.write("		location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/payment/payresult.pay?cids='+cid_arr+'&ophone='+ophone+'&oaddress='+oaddress\n");
      out.write("																							+'&directgID='+directgID+'&directoQTY='+directoQTY;\n");
      out.write("	}\n");
      out.write("</script>\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/checkout06.js\"></script>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /payment/checkout06.jsp(8,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("checkoutList");
      // /payment/checkout06.jsp(8,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.checkoutList }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /payment/checkout06.jsp(9,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("memberInfo");
      // /payment/checkout06.jsp(9,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.memberInfo }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f2_reused = false;
    try {
      _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f2.setParent(null);
      // /payment/../header/header.jsp(27,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setVar("userID");
      // /payment/../header/header.jsp(27,1) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.sessionId}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
      if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      _jspx_th_c_005fset_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("					");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("				");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /payment/../header/header.jsp(38,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionId eq null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("						<li class= login>\n");
          out.write("							<a id=\"log_change\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/IDPW/login.jsp\">로그인</a>\n");
          out.write("						</li>\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("						<li class= login>\n");
          out.write("							<a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/lobby/mypage.spm\">마이페이지</a>\n");
          out.write("						</li>\n");
          out.write("						<li class= login>\n");
          out.write("							");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님 환영합니다.&nbsp;&nbsp;&nbsp;\n");
          out.write("							<a href=\"#\" onclick= \"location.href='");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/main/sessionInitialization.jsp'\">로그아웃</a>\n");
          out.write("						</li>\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
