/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.79
 * Generated at: 2022-06-30 12:02:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.AD_002dPage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Goodslist2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/Goodslist.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<!-- 포장 시작 -->\r\n");
      out.write("	<div class=\"wrap\">\r\n");
      out.write("		<div class=wrap1-1>\r\n");
      out.write("			<!-- 타이틀 문구 -->\r\n");
      out.write("			<header class=\"page-title\">\r\n");
      out.write("				<h3>상품재고관리</h3>\r\n");
      out.write("			</header>\r\n");
      out.write("			<!-- 타이틀 문구  끝-->\r\n");
      out.write("\r\n");
      out.write("			<!-- 상다 메뉴 문구 -->\r\n");
      out.write("			<menu>\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li>전체 목록</li>\r\n");
      out.write("					<li>전체 상품 갯수</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</menu>\r\n");
      out.write("			<!-- 상다 메뉴 문구 끝-->\r\n");
      out.write("\r\n");
      out.write("			<br> <br>\r\n");
      out.write("\r\n");
      out.write("			<!-- 검색창 -->\r\n");
      out.write("			<div class=\"search\">\r\n");
      out.write("				<input type=\"text\" class=\"textBar\"> <i class=\"fas fa-search\"></i>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- 검색창 끝 -->\r\n");
      out.write("			<br>\r\n");
      out.write("\r\n");
      out.write("			<!-- 표 시작 -->\r\n");
      out.write("\r\n");
      out.write("			<table class=\"stock-list\" summary=\"상품명, 재고 주문대기, 재고수정\">\r\n");
      out.write("				<colgroup>\r\n");
      out.write("					<!-- 테이블	의 각 열의 크기 조절 가능 -->\r\n");
      out.write("					<col width=\"50\">\r\n");
      out.write("					<col width=\"300\">\r\n");
      out.write("					<col width=\"200\">\r\n");
      out.write("					<col width=\"200\">\r\n");
      out.write("					<col width=\"200\">\r\n");
      out.write("					<col width=\"300\">\r\n");
      out.write("					<col width=\"300\">\r\n");
      out.write("				</colgroup>\r\n");
      out.write("\r\n");
      out.write("				<thead>\r\n");
      out.write("					<tr class=\"list-title-tr\">\r\n");
      out.write("					<td class=\"editable\">x</td>\r\n");
      out.write("						<td class=\"editable\">상품 이미지</td>\r\n");
      out.write("						<td class=\"editable\">상품명</td>\r\n");
      out.write("						<td class=\"editable\">브랜드</td>\r\n");
      out.write("						<td class=\"editable\">가격</td>\r\n");
      out.write("						<td class=\"editable\">재고</td>\r\n");
      out.write("						<td class=\"editable\" style=\"background-color: #ffeccd;\">재고수정</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</thead>\r\n");
      out.write("\r\n");
      out.write("				<tbody>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th><input class=\"selectbox\" type=\"checkbox\" name=\"checkcel\"></th>\r\n");
      out.write("						<th class=\"img\">img</th>\r\n");
      out.write("						<th>상품1</th>\r\n");
      out.write("						<th>브랜드1</th>\r\n");
      out.write("						<th>1013400</th>\r\n");
      out.write("						<th>314</th>\r\n");
      out.write("						<th class=\"edit-part\"><input class=\"update-cell\" type=\"text\">\r\n");
      out.write("						</th>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th><input class=\"selectbox\" type=\"checkbox\" name=\"checkcel\"></th>\r\n");
      out.write("						<th class=\"img\">img</th>\r\n");
      out.write("						<th>상품2</th>\r\n");
      out.write("						<th>브랜드2</th>\r\n");
      out.write("						<th>100120</th>\r\n");
      out.write("						<th>116</th>\r\n");
      out.write("						<th class=\"edit-part\"><input class=\"update-cell\" type=\"text\">\r\n");
      out.write("						</th>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th><input class=\"selectbox\" type=\"checkbox\" name=\"checkcel\"></th>\r\n");
      out.write("						<th class=\"img\">img</th>\r\n");
      out.write("						<th>상품3</th>\r\n");
      out.write("						<th>브랜드3</th>\r\n");
      out.write("						<th>143420</th>\r\n");
      out.write("						<th>100</th>\r\n");
      out.write("						<th class=\"edit-part\"><input class=\"update-cell\" type=\"text\">\r\n");
      out.write("						</th>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th><input class=\"selectbox\" type=\"checkbox\" name=\"checkcel\"></th>\r\n");
      out.write("						<th class=\"img\">img</th>\r\n");
      out.write("						<th>상품4</th>\r\n");
      out.write("						<th>브랜드4</th>\r\n");
      out.write("						<th>11340</th>\r\n");
      out.write("						<th>240</th>\r\n");
      out.write("						<th class=\"edit-part\"><input class=\"update-cell\" type=\"text\">\r\n");
      out.write("						</th>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th><input class=\"selectbox\" type=\"checkbox\" name=\"checkcel\"></th>\r\n");
      out.write("						<th class=\"img\">img</th>\r\n");
      out.write("						<th>상품5</th>\r\n");
      out.write("						<th>브랜드5</th>\r\n");
      out.write("						<th>112310</th>\r\n");
      out.write("						<th>12</th>\r\n");
      out.write("						<th class=\"edit-part\"><input class=\"update-cell\" type=\"text\">\r\n");
      out.write("						</th>\r\n");
      out.write("					</tr>\r\n");
      out.write("					\r\n");
      out.write("				</tbody>\r\n");
      out.write("			</table>\r\n");
      out.write("\r\n");
      out.write("			<!-- 표 끝 -->\r\n");
      out.write("\r\n");
      out.write("			<br>\r\n");
      out.write("\r\n");
      out.write("			<div>\r\n");
      out.write("				<form class=\"btn\">\r\n");
      out.write("					<input type=\"button\" value=\"일괄수정\">\r\n");
      out.write("					<input onclick=\"localtion.href='ADDgoods.jsp'\" type=\"button\" value=\"상품추가\">\r\n");
      out.write("					<input type=\"button\" value=\"상품삭제\"\r\n");
      out.write("						onclick=\"deleteRow(-1)\">\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("<!-- <script src=\"Goodslist.js\"></script> -->\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
