/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.79
 * Generated at: 2022-06-15 13:47:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class personalinfrom_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/main/../footer/footer.jsp", Long.valueOf(1655202050815L));
    _jspx_dependants.put("/main/../header/header.jsp", Long.valueOf(1655202050743L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/personalinfrom.css\">\r\n");
      out.write("</head>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/main_css.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class= header>\r\n");
      out.write("			<a href=\"#\"onclick=\"location.href='../main/main.jsp'\" class= logo><img src= ../img/logo.png></a>\r\n");
      out.write("			<ul class = nav1>\r\n");
      out.write("				<li class= service><a href= \"center\">고객센터</a></li>\r\n");
      out.write("				<li class= basket><a href= \"basket\">장바구니</a></li>\r\n");
      out.write("				<li class= login><a href= \"login\">로그인</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			<br>\r\n");
      out.write("		<div class=\"search1\">\r\n");
      out.write("			<input type=\"text\" placeholder=\"Search\" class= search>\r\n");
      out.write("			<a class=\"btn\" href=\"serch.html\" role=\"button\">\r\n");
      out.write("			<img src=\"https://s3.ap-northeast-2.amazonaws.com/cdn.wecode.co.kr/icon/search.png\">\r\n");
      out.write("			</a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"category\">\r\n");
      out.write("		<div class= nav2>\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li><a href=\"#\" class=\"a\">냉장고</a>\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"shop1.html\">상품1</a></li>\r\n");
      out.write("						<li><a href=\"shop2.html\">상품2</a></li>\r\n");
      out.write("						<li><a href=\"shop3.html\">상품3</a></li>\r\n");
      out.write("						<li><a href=\"shop3.html\">상품4</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li><a href=\"#\" class=\"a\">세탁기</a>\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"shop1.html\">상품1</a></li>\r\n");
      out.write("						<li><a href=\"shop2.html\">상품2</a></li>\r\n");
      out.write("						<li><a href=\"shop3.html\">상품3</a></li>\r\n");
      out.write("					</ul></li>\r\n");
      out.write("				<li><a href=\"#\" class=\"a\">TV</a>\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"shop1.html\">상품1</a></li>\r\n");
      out.write("						<li><a href=\"shop2.html\">상품2</a></li>\r\n");
      out.write("					</ul></li>\r\n");
      out.write("				<li><a href=\"#\" class=\"a\">에어컨</a>\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"shop1.html\">상품1</a></li>\r\n");
      out.write("						<li><a href=\"shop2.html\">상품2</a></li>\r\n");
      out.write("						<li><a href=\"shop3.html\">상품3</a></li>\r\n");
      out.write("					</ul></li>\r\n");
      out.write("\r\n");
      out.write("				<li><a href=\"#\" class=\"a\">컴퓨터</a>\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"shop1.html\">상품1</a></li>\r\n");
      out.write("						<li><a href=\"shop2.html\">상품2</a></li>\r\n");
      out.write("						<li><a href=\"shop3.html\">상품3</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<script>\r\n");
      out.write("/* 	<a href=\"#\" onclick=\"delchk();\">삭제하기</a>\r\n");
      out.write("	\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("	function delchk(){\r\n");
      out.write("	    if(confirm(\"삭제하시겠습니까?\")){\r\n");
      out.write("	        location.href = \"write_del_ok.jsp?num=1\";\r\n");
      out.write("	        return true;\r\n");
      out.write("	    } else {\r\n");
      out.write("	        return false;\r\n");
      out.write("	    }\r\n");
      out.write("	} */\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"container\" class=\"css\">\r\n");
      out.write("		<div class=\"content\">\r\n");
      out.write("			<h2 class=\"cate_tit write\"><span class=\"icon\"></span>개인정보처리방침</h2></br><br>\r\n");
      out.write("			<div class=\"mt30 u-editor terms\">\r\n");
      out.write("				<h3>개인정보 수집· 이용에 관한 동의 </h3>\r\n");
      out.write("\r\n");
      out.write("				<h4>1. 개인정보의 수집· 이용 목적 </h4>\r\n");
      out.write("\r\n");
      out.write("				<p class=\"ml10\">퍼스트밴딩은 다음의 목적을 위하여 개인정보를 처리하고 있으며, 다음의 목적 이외의 용도로는 이용하지 않습니다</p>\r\n");
      out.write("				<ul class=\"ml30 mt10\">\r\n");
      out.write("					<li>1)	구매 및 결제 상담 관련 제안</li>\r\n");
      out.write("					<li>2)	구매 및 결제 상담 관련 접수</li>\r\n");
      out.write("					<li>3)	결제 및 배송지 정보 등</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("\r\n");
      out.write("				<h4>2. 수집· 이용하는 개인정보의 항목 </h4>\r\n");
      out.write("				<p class=\"ml10\">개인식별정보 (성명, 연락처, 주소)</p>\r\n");
      out.write("\r\n");
      out.write("				<h4>3. 개인정보의 보유 및 이용기간 </h4>\r\n");
      out.write("				<p class=\"ml10\">1) 수집된 개인정보는 이용목적이 달성된 후 지체 없이 파기됩니다.</p>\r\n");
      out.write("				<p class=\"ml10\">2) 구체적인 개인정보 처리 및 보유 기간은 다음과 같습니다.</p>\r\n");
      out.write("				<p class=\"ml30\">① 고객 상담 및 신청접수</p>\r\n");
      out.write("				<p class=\"ml50\"> 상담 고객정보 :  상담 후 24시간 이내 파기<br>\r\n");
      out.write("					상담 접수 고객정보 : 상담 접수, 심사 및 배송완료 후 30일 이내 파기<br>\r\n");
      out.write("					단, 채권/채무 관계 잔존 시 해당 채권/채무관계 정산 시 까지\r\n");
      out.write("				</p>\r\n");
      out.write("				<p class=\"ml10 mt10\">귀하는 동의를 거부할 권리가 있으나, 이에 대한 동의가 없을 경우, 구매 상담이 불가능할 수 있음을 알려 드립니다.</p>\r\n");
      out.write("\r\n");
      out.write("				<h4>4. 이용자 및 법정대리인의 권리와 그 행사방법</h4>\r\n");
      out.write("				<p class=\"ml10\">① 정보주체는 퍼스트밴딩 에 대해 언제든지 다음 각 호의 개인정보 보호 관련 권리를 행사할 수 있습니다.</p>\r\n");
      out.write("				<ul class=\"ml30 mt10\">\r\n");
      out.write("					<li>1)	개인정보 열람요구</li>\r\n");
      out.write("					<li>2)	오류 등이 있을 경우 정정 요구</li>\r\n");
      out.write("					<li>3)	삭제 요구</li>\r\n");
      out.write("					<li>4)	처리정지 요구</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("				<p class=\"ml10 mt10\">② 제1항에 따른 권리 행사는 회사에 대해 서면, 전화, 전자우편, FAX 등을 통하여 하실 수 있으며, 회사는 이에 대해 지체없이 조치하겠습니다.</p>\r\n");
      out.write("				<p class=\"ml10\">③ 정보주체가 개인정보의 오류 등에 대한 정정 또는 삭제를 요구한 경우에는 회사는 정정 또는 삭제를 완료할 때 까지 당해 개인정보를 이용하거나 제공하지 않습니다.</p>\r\n");
      out.write("				<p class=\"ml10\">④ 제1항에 따른 권리 행사는 정보주체의 법정대리인이나 위임을 받은 자 등 대리인을 통하여 하실 수 있습니다. 이 경우 개인정보 보호법 시행규칙 별지 제11호 서식에 따른 위임장을 제출하셔야 합니다.</p>\r\n");
      out.write("				<p class=\"ml10\">⑤ 정보주체는 개인정보보호법 등 관계법령을 위반하여 회사가 처리하고 있는 정보주체 본인이나 타인의 개인정보 및 사생활을 침해하여서는 아니됩니다.</p>\r\n");
      out.write("\r\n");
      out.write("				<h4>5. 이용자의 정보 자동수집장치의 설치 및 운영</h4>\r\n");
      out.write("				<p class=\"ml10\">회사는 정보주체의 이용정보를 저장하고, ‘쿠키(cookie)’를 사용하지 않습니다.</p>\r\n");
      out.write("\r\n");
      out.write("				<h4>6. 개인정보책임자</h4>\r\n");
      out.write("				<p class=\"ml10\">회사는 개인정보 처리에 관한 업무를 총괄해서 책임지고, 개인정보 처리와 관련한 이용자의 불만처리 및 피해구제 등을 위하여 아래와 같이 개인정보보호 책임자 및 담당부서를 지정, 운영하고 있습니다.</p>\r\n");
      out.write("									<p class=\"ml10 mt20\">▶ 개인정보 처리방침 담당자 정보</p>\r\n");
      out.write("					<p class=\"ml30\">- 담당부서 : </p>\r\n");
      out.write("					<p class=\"ml30\">- 책임자 : </p>\r\n");
      out.write("					<p class=\"ml30\">- 연락처 : </p>\r\n");
      out.write("					<p class=\"ml30\">- 이메일 : </p>\r\n");
      out.write("\r\n");
      out.write("					<p class=\"ml30\">- 담당자 : 김시우</p>\r\n");
      out.write("					<p class=\"ml30\">- 연락처 : 010-6123-5456</p>\r\n");
      out.write("					<p class=\"ml30\">- 이메일 :93jow@gmail.com</p>\r\n");
      out.write("					\r\n");
      out.write("				<p class=\"ml10 mt20\">이용자는 회사의 서비스(또는 사업)를 이용하시면서 발생한 모든 개인정보보호관련 문의, 불만처리, 피해구제 등에 관한 사항을 개인정보보호 책임자 및 담당부서로 문의하실 수 있습니다. 회사는 이용자의 문의에 대해 답변 및 처리해 드릴 것입니다.</p>\r\n");
      out.write("\r\n");
      out.write("				<p class=\"mt20\">기타 개인정보침해에 대한 신고나 상담이 필요하신 경우에는 아래 기관에 문의하시기 바랍니다.</p>\r\n");
      out.write("				<p class=\"mt10\">\r\n");
      out.write("					1. 개인정보침해신고사업단 <span class=\"show-375\"></span>(www.118.or.kr / 국번없이 118)<br>\r\n");
      out.write("					2. 대검찰청 사이버범죄수사단 <span class=\"show-375\"></span>(www.spo.go.kr / 02-3480-2000)<br>\r\n");
      out.write("					3. 경찰청 사이버테러대응사업단 <span class=\"show-375\"></span>(www.ctrc.go.kr / 1566-0112)\r\n");
      out.write("				</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div><!-- END Content -->\r\n");
      out.write("	</div>\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/main_css.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- footer -->\r\n");
      out.write("	<footer>\r\n");
      out.write("		<p>\r\n");
      out.write("			<span>상호명 : 구십삼</span>\r\n");
      out.write("			<span>대표 : 김시우</span><br/>\r\n");
      out.write("			<span>이메일 : 93jow@gmail.com</span><br>\r\n");
      out.write("			<span>주소 : 서울 강남구 테헤란로 146</span><br/>\r\n");
      out.write("			<span>사업자등록번호 : 000-00-0000</span><br/>\r\n");
      out.write("			<span>Copyright 2022. cocoder. All Rights Reserved.</span>\r\n");
      out.write("		</p>\r\n");
      out.write("			<a href=\"\" target='blank'>사이트관리자</a>\r\n");
      out.write("			<a href=\"\" target='blank'>회사소개</a>\r\n");
      out.write("			<a href=\"\" target='blank'>찾아오시는 길</a>\r\n");
      out.write("			<a href=\"#\" onclick=\"location.href='../main/personalinfrom.jsp'\"> 개인정보처리방침</a>\r\n");
      out.write("	</footer>\r\n");
      out.write("	\r\n");
      out.write("	<script>\r\n");
      out.write("	\r\n");
      out.write("	</script>\r\n");
      out.write("</html>\r\n");
      out.write("</body>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
