/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.79
 * Generated at: 2022-06-11 08:28:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.MyPage.lobby;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Mypage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>연매출구심3조-구십삼-마이로비</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"..\\css\\Mypage.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<header> ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "..\\common\\header.jsp", out, false);
      out.write(" </header>\r\n");
      out.write("	<div class=\"design_part\">마이페이지</div>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<!-- 마이페이지 메뉴 시작-->\r\n");
      out.write("		<div class=\"my-nav\">\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li><a\r\n");
      out.write("					onclick=\"location.href='..\\\\OrderList\\\\OrderList-Page.jsp'\"\r\n");
      out.write("					style=\"cursor: pointer;\">주문내역</a></li>\r\n");
      out.write("				<li><a\r\n");
      out.write("					onclick=\"window.open('shopping_basket.html', '장바구니','width=1200, height=800, left=0, top=0');\"\r\n");
      out.write("					style=\"cursor: pointer;\">장바구니</a></li>\r\n");
      out.write("				<li><a href=\"review.html\" style=\"cursor: pointer;\">상품리뷰</a></li>\r\n");
      out.write("				<li><a\r\n");
      out.write("					onclick=\"location.href='..\\\\Info\\\\User-Info.jsp'\"\r\n");
      out.write("					style=\"cursor: pointer;\">회원정보수정</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- 마이페이지 메뉴 끝-->\r\n");
      out.write("		\r\n");
      out.write("		<br> <br>\r\n");
      out.write("	\r\n");
      out.write("		<div class=\"order\">\r\n");
      out.write("			<h3 style=\"width: 150px; text-align: center; font-weight: bold;\">최근\r\n");
      out.write("				주문 목록</h3>\r\n");
      out.write("			<a class=\"more_view\"\r\n");
      out.write("				onclick=\"location.href='..\\\\OrderList\\\\OrderList-Page.jsp'\"\r\n");
      out.write("				style=\"font-size: 13px; cursor: pointer;\">더보기 +</a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<table class=\"order_tb\" summary=\"주문일자, 상품명, 결제금액, 주문상세\"\r\n");
      out.write("			style=\"border-top: 1px solid black;\">\r\n");
      out.write("			<colgroup>\r\n");
      out.write("				<col width=\"150\">\r\n");
      out.write("				<col width=\"*\">\r\n");
      out.write("				<col width=\"140\">\r\n");
      out.write("				<col width=\"140\">\r\n");
      out.write("			</colgroup>\r\n");
      out.write("			<!-- 표의 제목 부분  시작-->\r\n");
      out.write("			<thead>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>\r\n");
      out.write("						<div class=\"tab-center\">주문일자</div>\r\n");
      out.write("					</td>\r\n");
      out.write("					<td>\r\n");
      out.write("						<div class=\"tab-center\">상품명</div>\r\n");
      out.write("					</td>\r\n");
      out.write("					<td>\r\n");
      out.write("						<div class=\"tab-center\">결제금액</div>\r\n");
      out.write("					</td>\r\n");
      out.write("					<td>\r\n");
      out.write("						<div class=\"tab-center\">상세정보</div>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</thead>\r\n");
      out.write("			<!-- 표의 제목 부분  끝-->\r\n");
      out.write("			<!-- 표의 본문 시작 -->\r\n");
      out.write("			<tbody class=\"table-body\">\r\n");
      out.write("				<tr>\r\n");
      out.write("<!-- 				<td colspan=\"\"> -->\r\n");
      out.write("<!-- 					<div class=\"tab-center\">주문 내역이 없습니다.</div> -->\r\n");
      out.write("<!-- 				</td> -->\r\n");
      out.write("					<td>\r\n");
      out.write("						YY-MM-DD\r\n");
      out.write("					</td>\r\n");
      out.write("					<td>\r\n");
      out.write("						test product\r\n");
      out.write("					</td>\r\n");
      out.write("					<td>\r\n");
      out.write("						test price\r\n");
      out.write("					</td>\r\n");
      out.write("					<td>\r\n");
      out.write("						more information\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>\r\n");
      out.write("						YY-MM-DD\r\n");
      out.write("					</td>\r\n");
      out.write("					<td>\r\n");
      out.write("						test product2\r\n");
      out.write("					</td>\r\n");
      out.write("					<td>\r\n");
      out.write("						test price\r\n");
      out.write("					</td>\r\n");
      out.write("					<td>\r\n");
      out.write("						more information\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>\r\n");
      out.write("						YY-MM-DD\r\n");
      out.write("					</td>\r\n");
      out.write("					<td>\r\n");
      out.write("						test product3\r\n");
      out.write("					</td>\r\n");
      out.write("					<td>\r\n");
      out.write("						test price\r\n");
      out.write("					</td>\r\n");
      out.write("					<td>\r\n");
      out.write("						more information\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</tbody>\r\n");
      out.write("			<!-- 표의 본문 끝-->\r\n");
      out.write("		</table>\r\n");
      out.write("		\r\n");
      out.write("	<br> <br>\r\n");
      out.write("\r\n");
      out.write("	<footer> ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "..\\common\\footer.jsp", out, false);
      out.write(" </footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
