/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.79
 * Generated at: 2022-06-30 13:12:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Info;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class secession_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<!-- <link rel=\"stylesheet\" type=\"text/css\" href=\"../css/secession.css\"> -->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<header> ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../header/header.jsp", out, false);
      out.write(" </header>\r\n");
      out.write("	<span class=\"secession\">\r\n");
      out.write("	<div class=\"wrap\">\r\n");
      out.write("		<header class=\"secession-title\"> <h1 class=\"title-text\">회원 탈퇴</h1> </header>\r\n");
      out.write("		<div class=\"secession-text\">\r\n");
      out.write("			<p><span>회원님 구십삼 서비스를 이용하는데 불편함이 있으셨나요?</span></p>\r\n");
      out.write("			\"1)이용 불편 및 각종 문의 사항은 고객센터로 문의주시면 성심 성의껏 답변 드리겠습니다.\"<br>\r\n");
      out.write("			\"- 전화 문의: 1577-0093 (366일 오전 10시 ~ 오후 6시)\"\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"secession-box\">\r\n");
      out.write("			<div class=\"secession-box-text\">\r\n");
      out.write("				<section>\r\n");
      out.write("					<h1>1. 회원탈퇴 전, 유의사항을 확인해 주시기 바랍니다.</h1>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li>\r\n");
      out.write("							- 회원탈퇴 시 회원전용 웹 서비스 이용이 불가합니다.\r\n");
      out.write("							</li>\r\n");
      out.write("							<li>\r\n");
      out.write("							- 거래정보가 있는 경우, 전자상거래 등에서의 소비자 보호에 관한 법률에 따라 계약 또는 청약철회에 관한 기록, 대금결제 및 재화 등의 공급에 관한 기록은 5년동안 보존됩니다.\r\n");
      out.write("							</li>\r\n");
      out.write("							<li>\r\n");
      out.write("							- 회원탈퇴 후 쿠팡 서비스에 입력하신 상품문의 및 후기, 댓글은 삭제되지 않으며, 회원정보 삭제로 인해 작성자 본인을 확인할 수 없어 편집 및 삭제처리가 원천적으로 불가능 합니다.<br>\r\n");
      out.write("							상품문의 및 후기, 댓글 삭제를 원하시는 경우에는 먼저 해당 게시물을 삭제하신 후 탈퇴를 신청하시기 바랍니다.\r\n");
      out.write("							</li>\r\n");
      out.write("							<li>이미 결제가 완료된 건은 탈퇴로 취소되지 않습니다.</li>\r\n");
      out.write("						</ul>\r\n");
      out.write("				</section>\r\n");
      out.write("			</div>\r\n");
      out.write("				<div class=\"secession-confirm\">\r\n");
      out.write("					<label class=\"secession-confirm-checkbox\">\r\n");
      out.write("						<input class=\"secession-checkbox\" type=\"checkbox\" name=\"secessioncheckbox\" data-type=\"checked\" data-err=\"alert\" data-err-msg=\"탈퇴 처리사항 안내 확인에 동의해주세요.\">\r\n");
      out.write("						<span>상기 구십삼 회원탈퇴 시 처리사항 안내를 확인하였음에 동의합니다.</span>\r\n");
      out.write("					</label>\r\n");
      out.write("				</div>\r\n");
      out.write("		\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"secession-validate-user\">\r\n");
      out.write("            <p class=\"secession-validate-user-msg\">\r\n");
      out.write("                <strong>보안을 위해 회원님의 이름과 계정 이메일 및 비밀번호를 확인 합니다.</strong>\r\n");
      out.write("            </p>\r\n");
      out.write("            <label>\r\n");
      out.write("                <span>이름 : </span>\r\n");
      out.write("                <input class=\"secession-validate-user-name\" type=\"text\" readonly=\"\" value=\"#\" style=\"background-color: #eae0ed; border: 1px solid black;\">\r\n");
      out.write("            </label>\r\n");
      out.write("            <label>\r\n");
      out.write("                <span>이메일 : </span>\r\n");
      out.write("                <input class=\"secession-validate-user-email\" type=\"text\" readonly=\"\" value=\"ksh980326@naver.com\" style=\"background-color: #eae0ed; border: 1px solid black;\">\r\n");
      out.write("            </label>\r\n");
      out.write("            <label>\r\n");
      out.write("                <span>비밀번호 : </span>\r\n");
      out.write("                <input class=\"secession-validate-user-password\" type=\"password\" id=\"password\" name=\"password\" data-err-target=\"alert\" data-err-msg=\"비밀번호를 입력하세요.\" >\r\n");
      out.write("            </label>\r\n");
      out.write("            <button type=\"submit\" class=\"secession-validate-user-submit\">본인확인 & 회원탈퇴</button>\r\n");
      out.write("        </div>\r\n");
      out.write("	</div>\r\n");
      out.write("	</span>\r\n");
      out.write("\r\n");
      out.write("	<footer> ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../footer/footer.jsp", out, false);
      out.write(" </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
